### ISSUE TITLE
Move to Camunda Community Hub?

### ISSUE THREAD

**Issue by jwulf** [camunda-community-hub/zeebest#27]
Hi Mackenzie, we have a new [Camunda Community Hub](https://github.com/camunda-community-hub/) for hosting community extension. What do you think about moving Zeebest there? It will give it some more surface area and may help in find new contributors / maintainers.

**Comment by xmclark** [comment]
@jwulf hey there! I think that's an excellent idea. Where do I go?

**Comment by jwulf** [comment]
We're moving repos, rather than forking them, to avoid having to keep multiple repos in sync and having one canonical upstream. If you're OK with transferring it to the Community Hub, we'd give you maintainer permissions on the repo there?

**Comment by xmclark** [comment]
If that works best for you. I have no concerns. Would you like me to add you as admin on this repo, and you can do the rest?

**Comment by jwulf** [comment]
Sure, that works.

**Comment by jwulf** [comment]
I have push access, but can't transfer. Can you do that? Here are the instruction in the Community Hub README, it's just two clicks.

https://github.com/camunda-community-hub/community#getting-started

**Comment by jwulf** [comment]
Moved successfully!
